In [13]:
# 1) Create an array, as strings, of all the numbers between 44 and 59.
L = list(range(44, 60))
L

[44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59]

In [34]:
import numpy as np
A = np.array(L, dtype='str')
A

array(['44', '45', '46', '47', '48', '49', '50', '51', '52', '53', '54',
       '55', '56', '57', '58', '59'], dtype='<U2')

In [29]:
# 2) Using the math function, create a NumPy array of the Square Roots of all numbers between 3 and 18
import math
square_list = list(math.sqrt(x) for x in range(3, 19))
np.array(square_list)

array([1.73205081, 2.        , 2.23606798, 2.44948974, 2.64575131,
       2.82842712, 3.        , 3.16227766, 3.31662479, 3.46410162,
       3.60555128, 3.74165739, 3.87298335, 4.        , 4.12310563,
       4.24264069])

In [73]:
# 3) Create an array six random numbers in the range from 1 to 49, inclusive (min 1, max 49).
random_list = np.random.randint(1, 50, size = 6)
random_list

array([36, 41, 29, 37, 48,  5])

In [76]:
# 4) create an array that is the combination of the arrays from Steps 2 and 3. What is the data type of the first element? the last element? (Determine with a Python command)
arr = np.concatenate([square_list, random_list])
arr

array([ 1.73205081,  2.        ,  2.23606798,  2.44948974,  2.64575131,
        2.82842712,  3.        ,  3.16227766,  3.31662479,  3.46410162,
        3.60555128,  3.74165739,  3.87298335,  4.        ,  4.12310563,
        4.24264069, 36.        , 41.        , 29.        , 37.        ,
       48.        ,  5.        ])

In [42]:
arr.dtype
# both are float64

dtype('float64')

In [75]:
# 5) Create another array that corresponds to the 5th through 10th item of the array in Step 4.
arr[5:11]

array([2.82842712, 3.        , 3.16227766, 3.31662479, 3.46410162,
       3.60555128])

In [77]:
# 6) Use a fast function to change the array in Step 4 to hold the Square of each of the values, using either the pow() function of Python's math class or the ** operator.
arr = np.array(list(num**2 for num in arr))
arr

array([   3.,    4.,    5.,    6.,    7.,    8.,    9.,   10.,   11.,
         12.,   13.,   14.,   15.,   16.,   17.,   18., 1296., 1681.,
        841., 1369., 2304.,   25.])

In [78]:
# 7) Sum up all the items in the array in Step 6, showing intermediate values along the way.
np.add.reduce(arr)

7684.0

In [82]:
# 8) Obtain the minimum, maximum, and average of all the items in the array in Step 6.
np.min(arr)

2.9999999999999996

In [83]:
np.max(arr)

2304.0

In [85]:
np.mean(arr)

349.27272727272725

In [91]:
# 9) Produce a plot of the heights of US Presidents.
import pandas as pd
data = pd.read_csv('president_heights.csv')
heights = np.array(data['height(cm)'])
np.mean(heights)

179.73809523809524

In [97]:
# 10) How many days in 2014 were there more than 1 inch of rain? What was the total annual rainfall in inches? Millimeters?
rainfall = pd.read_csv('Seattle2014.csv')['PRCP'].values
inches = rainfall / 254.0  
count = 0
for inch in inches:
    if inch > 1: count+=1
count

7

In [98]:
np.add.reduce(inches)

48.535433070866134

In [99]:
np.add.reduce(inches*25.4)

1232.8